# Generated by Django 4.0.1 on 2022-01-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csfd_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='Actors',
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
        migrations.AlterModelTable(
            name='actors',
            table='actors',
        ),
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
