# Generated by Django 4.0.1 on 2022-01-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csfd_app', '0002_rename_actor_actors_rename_movie_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='csfd_app.Movies'),
        ),
    ]
