# Generated by Django 4.0.1 on 2022-02-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csfd_app', '0003_alter_actors_movies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actors',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movies',
            table=None,
        ),
    ]
